name: 'push to git mirror with ssh key'
description: 'git push to mirror with ssh key'
author: 'cl0pinette'
runs:
  using: 'docker'
  image: 'Dockerfile'
  volumes:
    - "${{ secrets.PATH }}:~/.ssh/"
